server:
  port: 8001

spring:
  datasource:
    # ShardingSphere 对 Driver 自定义，实现分库分表等隐藏逻辑
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    # ShardingSphere 配置文件路径
    url: jdbc:shardingsphere:classpath:shardingsphere-config-${database.env:dev}.yaml
  mvc:
    view:
      prefix: /templates/
      suffix: .html
  data:
    redis:
      channel-topic:
        short-link-stats: 'short_link:stats-stream'
        short-link-stats-group: 'short_link:stats-stream:only-group'

short-link:
  domain:
    default: nurl.ink:8001
  stats:
    locale:
      amap-key: a446be873b6e7dc45541a898075dab51
  goto-domain:
    white-list:
      enable: true
      names: '知乎、百度'
      details:
        - baidu.com
        - zhihu.com


re:
  mq:
    - "1721220269138-0"
    - XADD "short_link:stats-stream" * "New key01313" "New value01313"
    -

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto
  mapper-locations: classpath:mapper/*.xml