server:
  port: 8001

spring:
  application:
    name: aa03-short-link-project
  datasource:
    # ShardingSphere 对 Driver 自定义，实现分库分表等隐藏逻辑
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    # ShardingSphere 配置文件路径
    url: jdbc:shardingsphere:classpath:shardingsphere-config-${database.env:dev}.yaml
  data:
    redis:
      host: common-redis-dev.magestack.cn
      port: 19389
      password: Sm9sVXBOYJjI030b5tz0trjpzvZzRhtZmEbv0uOImcD1wEDOPfeaqNU4PxHob/Wp
  cloud:
    nacos:
      discovery:
        server-addr: common-nacos-dev.magestack.cn:8848
  mvc:
    view:
      prefix: /templates/
      suffix: .html

short-link:
  domain:
    default: nurl.ink:8001
  stats:
    locale:
      amap-key: a446be873b6e7dc45541a898075dab51
  goto-domain:
    white-list:
      enable: true
      names: '知乎、百度'
      details:
        - baidu.com
        - zhihu.com

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto
  mapper-locations: classpath:mapper/*.xml

unique-name: aa03
framework:
  cache:
    redis:
      prefix: aa03

rocketmq:
  name-server: common-rocketmq-dev.magestack.cn:9876
  producer:
    group: aa03-short-link_project-service_stats-save_pg
    topic: aa03-short-link_project-service_topic
    send-message-timeout: 2000
    retry-times-when-send-failed: 1
    retry-times-when-send-async-failed: 1
  consumer:
    group: aa03-short-link_project-service_stats-save_cg